<?php

$a=10;
$b=5;

echo "1.  ";
echo "$a~$b~";
echo $hasil=$a+$b-2.5;
echo "<br>";
echo "2.       ";
echo "$a~";
echo $hasil=$b+1;
echo "~";
echo $hasil=$b-1.5;	
echo "<br>";
echo "3.       ";
echo "$a~";
echo $hasil=$b+1;
echo "~";
echo $hasil=$b-1.5;
echo "~";	
echo $hasil=$a*$b;
echo "<br>";
echo "4.   ";
echo $hasil=$a+1;
echo "~";
echo $hasil=$b+1;
echo "~";
echo $hasil=$b-$b*2-1.5;
echo "~"; 
echo $hasil=$a*$a+$b+1;
echo "<br>";
echo "5.    ";
echo $hasil=$a+1;
echo "~";
echo $b;
echo "~";
echo $hasil=$a-$a*2-0.5;
echo "<br>";
echo "6.   ";
echo $hasil=$a+3;
echo "~";
echo $hasil=$b-1;
echo "~";
echo $hasil=$b-$b*2-1.5;
echo "<br>";
echo "7.   ";
echo $hasil=$a+3;
echo "~";
echo $hasil=$b-1;
echo "~";
echo $hasil=$b-5*2-0.56;
echo "<br>";
echo "8.    ";
echo $hasil=$a+2;
echo "~";
echo $hasil=$b-2;
echo "~";
echo $hasil=$b-5*2-0.56;
echo "<br>";
echo "9.     ";
echo $hasil=$a+1;
echo "~";
echo $hasil=$b-1;
echo "~";
echo $hasil=$b-5*2-0.5;
echo "~";
echo $hasil=$a/$b+4;